### PR TITLE
Bundle SQLite

### PR DESCRIPTION
**Pull request by agersant**

### CODE REVIEW

**Comment by lnicola** [comment]
It would be nice to have a feature for this. On Linux it's pretty hard to not have SQLite installed.

**Comment by agersant** [comment]
> It would be nice to have a feature for this. On Linux it's pretty hard to not have SQLite installed.
That's a fair point, I'll add a feature toggle for this. (default will be bundled though)

> And you've changed the version to *, but diesel uses strict constraints: https://github.com/diesel-rs/diesel/blob/master/diesel/Cargo.toml#L19. Once a new libsqlite3-sys is released, you might have a version conflict between them.
I am unsure what a better way to do this. The end goal is to add the "bundled" feature to whatever version of `libsqlite3-sys` was selected to satisfy the `diesel` requirements, without pulling an additional version (which immediately fails the build as this is linking against a static library).

**Comment by lnicola** [comment]
IIRC the best way I found was to upgrade `libsqlite3-sys` in lockstep with `diesel`. Maybe they'd accept adding a pair of `sqlite3-bundled`/`sqlite3-bundled-windows` features.

**Comment by agersant** [comment]
Guess I'll go back to the lockstep, I don't have a strong preference.

**Pull request merged**
