### PR TITLE
Index optimizations

### PR DESCRIPTION
**Pull request by agersant**
Savings were:
- Moving all database insertions away from the thread doing directory traversal
- Avoiding bail!() macro on critical path
- Parallelizing the work to detect DB entries that should be removed

Net result is about 50% faster on warm cache, running on i7-8086k CPU and HDS722020ALA330 drive on Windows.

### CODE REVIEW

**Comment by lnicola** [comment]
This brought the rescan time on my setup down from 320 to 12 seconds :heart_eyes:.

I'm a bit conflicted about the error messages, though, especially as I get some false positives.

**Comment by agersant** [comment]
Wow, that is amazing! Is that on the old Celeron CPU? Do you have a lot of files that Polaris has to skip (cover art, cue files, etc.)? I did not anticipate such dramatic improvements.

I am also seeing a handful of error messages now that I deployed this to my production setup. They all look like: 
```
Error while reading file metadata for '"/media/leviathan/music/genres/Hip-Hop/Fakear/2013 - Morning in Japan/03 - Kids.mp3"': Parsing: delimiter not found
```

I'll investigate this one (tomorrow). Please let me know if yours look different.

**Comment by lnicola** [comment]
I've got 11 847 songs in the database and Polaris is scanning 19 326 files and directories.

Regarding the errors, I have a couple of different ones. I suspect that most of them are actually real, but some seem to be false positives:

- `InvalidInput: reader does not contain flac metadata`
- `Parsing: unknown encoding`
- `NoTag: reader does not contain an id3 tag`
- `Missing Vorbis comments`

**Comment by agersant** [comment]
These are all errors originating from the dependencies responsible for extracting metadata from the audio files. If you can share some of the false positive files, I'd be happy to investigate those too at some point.

**Comment by lnicola** [comment]
https://drive.google.com/open?id=1HmIaetMEBEBv-5zCyJE6jNknjQ4E76IY has a couple of examples. The encoding error for the MP3 might be a true positive. It looks all right, but I haven't checked.

Note that those aren't royalty-free songs, so I hope you don't feel uncomfortable downloading them. I wanted to extract the first couple of seconds but decided against it in case it affected the results. I did notice you were careful about this when preparing the Polaris screenshots in the README and on Play Store.

**Comment by agersant** [comment]
Thank you! I downloaded them so you can take them down now if you want. I think this would qualify as fair use of the files so I'm not too worried about it.

Fun fact is the Polaris app originally got rejected from the Google Play Store because the screenshots had a Stratovarius album cover art (if I remember correctly). I made the example Aegeus album in response to that, and I kept it for the README because I got attached to it. If you're curious, the illustration was painted by a friend who gave me permission to borrow it (https://pierreguyot.com/portfolio/character-design/#jp-carousel-134).

**Comment by agersant** [comment]
Some updates:

I investigated the files from my collection spending a lot of time in mp3_duration. They have no Xing header so the code has to jump through the entire file to compute how long the song is. Made a few improvements there for a 10% speed increase: https://github.com/agersant/mp3-duration/commit/8ab8fe530bbec55660af1bf7cb18bca34fb25f59 and https://github.com/agersant/mp3-duration/commit/8ab8fe530bbec55660af1bf7cb18bca34fb25f59

I also took a look at the files you sent:

The two FLAC files have their metadata in a ID3 tag at the beginning of the file, which does not conform to the [FLAC standard](https://xiph.org/flac/format.html#format_overview):
> VORBIS_COMMENT: [...] It is an implementation of the Vorbis comment specification (without the framing bit). **This is the only officially supported tagging mechanism in FLAC**.

A potential solution is to throw these files at the ID3 decoder after failing to read FLAC metadata. This works for the Dirty Dancing song except the title somehow ends up in both the title and artist fields. Foorbar2000 gets it right so this could be a bug in the id3 crate.

Using the same process, the ID3 tag in the Wintersun song fails to decode after hitting `StringDecoding([]): data is not valid utf-8`. This is the same error as the one triggered by the Romanian song. Empty string seems like a reasonable value for fields so this could also be a bug in the id3 crate. I'm going to look at this next.

**Comment by agersant** [comment]
The ID3 tag in the Wintersun file is incorrect. The header in the MCDI frame reports a length of 78 bytes but it actually has 79 bytes of content. The error most likely happened because whatever encoder worked on this file wrote the content length before it applied unsychronization (I see one unsynchronized pair in the frame).

As a result, the decoder starts looking for a frame header one byte too early and reads `[0xFF, T, L, E]` (which isn't valid UTF-8) instead of `[T, L, E, N]` for the next header. Unfortunately, rust-id3 does not return partial tags when it encounters an error so we have no access to the previous frames that were successfully decoded. I'll open an issue on the ID3 repository to see if that's a feature they would consider adding.

**Comment by agersant** [comment]
Finally, the ID3 tag in the Romanian song is also incorrectly encoded. The `APIC` frame size is encoded as 0x0000E805 (1110 1000 0000 0101). After being synchsafe decoded, this becomes 0x7405 (111 0100 0000 0101).
It turns out the frame size is actually 0xE805 so it looks like this encoder wrote frame sizes as regular integers instead of synchsafe integers.

After this, something similar to the Wintersun file happens were we start looking for the next frame's header while still in the middle of the image data and it doesn't end well.

**Comment by lnicola** [comment]
Thanks for looking into it, that sounds like quite the ride.

`metaflac --list` (from the `flac` distribution) actually works with the two FLACs and returns `VORBIS_COMMENT` blocks that look fine. So they have both the FLAC and ID3 metadata. And the Dirty Dancing one has indeed the song name in the performer field.

I also found this nice gem:

```
FLAC.EXE -6 -V -T "ARTIST=Wintersun" -T "TITLE=Death And The Healing" -T "ALBUM=Wintersun" -T "DATE=2004" -T "TRACKNUMBER=05" -T "GENRE=Extreme Power Metal" -T "COMMENT=" -T "BAND=" -T "ALBUMARTIST=" -T "COMPOSER=" --tag-from-file=LYRICS="C:\Users\Admin\AppData\Local\Temp\LYRD852.tmp" -T "DISCNUMBER=1" -T "TOTALDISCS=1" -T "TOTALTRACKS=8" --picture="C:\Users\Admin\AppData\Local\Temp\CPID851.tmp" -o
```

**Comment by agersant** [comment]
What does this FLAC command do?

When I said metaflac I meant the Rust library metaflac, not the standard .exe which seems a bit more tolerant.

**Comment by lnicola** [comment]
It's the encoder command line, stored in the file for whatever reason.

Yeah, I didn't expect the official FLAC tools to be so tolerant.

**Pull request merged**
