### PR TITLE
add mp3 duration

### PR DESCRIPTION
**Pull request by jxs**
meanwhile, while trying to calculate the bitrates of the remaning frames of the mp3 file, i found this crate `mp3-metadata` that does that while still parsing the id3 tag. But it gave me errors on some mp3 files, so I used it just for calculating the duration. It seemed very fast from what I tried
what do you think?
cheers :)

### CODE REVIEW

**Comment by agersant** [comment]
I ran this locally to test performance and it is way too slow. Indexing my collection (~75,000 mp3 files) usually takes minutes. With this change, it takes 103 minutes (consistent over two runs).

I took a quick look at the source of mp3-metadata and that code doesn't seem very good. In addition to doing a lot of work we don't need, it also allocates heap memory to store data about every frame in the file (which is bound to slow things down a lot).

This got me a bit more involved in the problem so I might try to write a crate just for that and make it as fast as I can.

**Comment by jxs** [comment]
my actual collection is way less short, (~300 files and 100 of them flac) and i didn't notice any difference, I also only saw the code birds eye and it seemed to only read the headers, didn't see that, my bad. 
And yeah I just tested with large files like 200 mb mp3 files and it starts to deteriorate.
I can do it, but if you want to do it go ahead :) I'll jump to mp4 parsing

**Comment by agersant** [comment]
Handled by 52835c4b97c573c49003d5e5ec450d600d017932, using https://github.com/agersant/mp3-duration.

**Comment by jxs** [comment]
wow fast! thanks 🙌

**Comment by agersant** [comment]
Update for posterity: index duration in the same conditions I tested above is at 20 minutes (which makes sense: we're poking at every mp3 file twice and the indexing is twice as long).

Ideally it would all be in one pass as you already mentioned in your original TODO. @jameshurst, would you be interested in a patch to id3 to read duration from Xing/Info headers (where length is stored by most modern mp3 encoders). Those are not strictly id3 but they are more common than the TLEN frame.

**Pull request closed without merging**
