### PR TITLE
add composer lyricist and genre tags

### PR DESCRIPTION
**Pull request by Saecki**
Add at least some more metadata as requested in #92 and #134.

### CODE REVIEW

**Comment by pmphfm** [comment]
FWIW, I have a similar patch on a forked repo. I am using/running the fork for a while now. Both android app and web clients show/display that info. Here https://github.com/pmphfm/polaris/commits/master . The maintainer was not willing to add more fields so I had to fork. I haven't pushed the client changes.

(For me information about the song is more important than the artwork)

**Comment by Saecki** [comment]
That looks nicer than my fork. Would you mind opening a PR in favor of this one?

**Comment by agersant** [comment]
For context, I was originally not super interested in merging the changes because the fields will have to change again to support multi-value for semantic browsing. That is still true today, but I now realize that the work for semantic browsing is many months away so there can be value merging a PR adding fields in the mean time.

**Comment by Saecki** [comment]
Closing in favor of #141.

**Pull request closed without merging**
